# Generated by Django 3.2.8 on 2021-10-13 21:33

import barter_and_inventory.utils
import barter_and_inventory.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=400)),
                ('category_status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_ACTIVE', 'In-active')], default='ACTIVE', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=400)),
                ('offer_description', models.TextField(max_length=1000)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estimated_cost_currency', models.CharField(choices=[('PKR', 'Pakistani Rupees'), ('INR', 'Indian Rupees'), ('EUR', 'Euros'), ('USD', 'United Stated Dollar'), ('CAD', 'Canadian Dollar'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CHF', 'Swiss Franc')], default='USD', max_length=255)),
                ('includes_cash', models.BooleanField(default=False)),
                ('cash_in_hand', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_in_hand_currency', models.CharField(blank=True, choices=[('PKR', 'Pakistani Rupees'), ('INR', 'Indian Rupees'), ('EUR', 'Euros'), ('USD', 'United Stated Dollar'), ('CAD', 'Canadian Dollar'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CHF', 'Swiss Franc')], default='USD', max_length=255, null=True)),
                ('exchange_date', models.DateTimeField(blank=True, null=True)),
                ('shipment_method', models.CharField(blank=True, choices=[('SELF_PICKUP', 'Self Pickup'), ('TRANSPORT', 'Transport'), ('COURIER', 'Courier')], default='USD', max_length=255, null=True)),
                ('shipment_address', models.CharField(blank=True, max_length=500, null=True)),
                ('final_remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_created_by', to=settings.AUTH_USER_MODEL)),
                ('exchanged_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='exchanged_with_offer', to='barter_and_inventory.offer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=400)),
                ('product_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], default='NEW', max_length=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('price_currency', models.CharField(choices=[('PKR', 'Pakistani Rupees'), ('INR', 'Indian Rupees'), ('EUR', 'Euros'), ('USD', 'United Stated Dollar'), ('CAD', 'Canadian Dollar'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CHF', 'Swiss Franc')], default='USD', max_length=255)),
                ('product_status', models.CharField(choices=[('OUT_OF_STOCK', 'Out of stock'), ('AVAILABLE', 'Available')], default='AVAILABLE', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_created_by', to=settings.AUTH_USER_MODEL)),
                ('product_categories', models.ManyToManyField(related_name='categories', to='barter_and_inventory.Category')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email_confirmed', models.BooleanField(blank=True, default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=barter_and_inventory.utils.user_profile_picture_upload_handler, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg']), barter_and_inventory.validators.validate_image_size])),
                ('initial_color', models.CharField(blank=True, default=barter_and_inventory.utils.initials_color_code_generator, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_photo', models.ImageField(upload_to=barter_and_inventory.utils.product_photo_upload_handler, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_picture_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_photos', to='barter_and_inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_picture_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Photo',
                'verbose_name_plural': 'Product Photos',
            },
        ),
        migrations.CreateModel(
            name='OfferProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_product_created_by', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_products', to='barter_and_inventory.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offer', to='barter_and_inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_product_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer Product',
                'verbose_name_plural': 'Offer Products',
            },
        ),
    ]
