# Generated by Django 3.2.8 on 2021-10-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter_and_inventory', '0003_offerbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('NEGOTIATION', 'Negotiation'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='OPEN', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='shipment_method',
            field=models.CharField(blank=True, choices=[('SELF_PICKUP', 'Self Pickup'), ('TRANSPORT', 'Transport'), ('COURIER', 'Courier')], default='SELF_PICKUP', max_length=255, null=True),
        ),
    ]
