# Generated by Django 3.2.8 on 2021-10-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter_and_inventory', '0004_auto_20211016_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerbid',
            name='product_quantity',
        ),
    ]
