# Generated by Django 3.2.8 on 2024-01-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter_and_inventory', '0009_alter_product_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_condition',
            field=models.CharField(choices=[('NEW', 'New'), ('USED', 'Used')], default='NEW', max_length=10),
        ),
    ]
